version: '2'
services:
    kafka-manager:
        image: intropro/kafka-manager
        container_name: kafka-manager
        ports:
            - "9001:9001"
        environment:
            ZK_HOSTS: localhost:2181
